// <auto-generated />
using Examen1_U1.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Examen1_U1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231022013600_EstudiantesTable")]
    partial class EstudiantesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EstudianteEstudiante", b =>
                {
                    b.Property<int>("EstudiantesEnTutoriaId")
                        .HasColumnType("int");

                    b.Property<int>("TutoresId")
                        .HasColumnType("int");

                    b.HasKey("EstudiantesEnTutoriaId", "TutoresId");

                    b.HasIndex("TutoresId");

                    b.ToTable("relacion_estudiantes", (string)null);
                });

            modelBuilder.Entity("Examen1_U1.Entities.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("correo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("numero_cuenta");

                    b.HasKey("Id");

                    b.ToTable("estudiantes");
                });

            modelBuilder.Entity("EstudianteEstudiante", b =>
                {
                    b.HasOne("Examen1_U1.Entities.Estudiante", null)
                        .WithMany()
                        .HasForeignKey("EstudiantesEnTutoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Examen1_U1.Entities.Estudiante", null)
                        .WithMany()
                        .HasForeignKey("TutoresId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
